// Build the spyglass page: bundle apps/cli/glass/src/main.ts (esbuild,
// one IIFE), minify apps/cli/glass/glass.css, inline both into
// apps/cli/glass/index.html, and emit the result as one string module,
// apps/cli/src/glass-page.generated.ts, which serveGlass imports. The page
// stays one self-contained document: no external files beyond the assets
// serveGlass already serves (icon, sprite, star).
//
//   node scripts/build-glass.mjs           build once (apps/cli's `build` runs this)
//   node scripts/build-glass.mjs --watch   rebuild on every change under apps/cli/glass (pnpm glass:dev)
//   node scripts/build-glass.mjs --dev     unminified, for reading the page source
import * as esbuild from 'esbuild';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const glass = path.join(root, 'apps', 'cli', 'glass');
const out = path.join(root, 'apps', 'cli', 'src', 'glass-page.generated.ts');
const distOut = path.join(root, 'apps', 'cli', 'dist', 'glass-page.generated.js');
const watch = process.argv.includes('--watch');
const minify = !watch && !process.argv.includes('--dev');

const CSS_TAG = '<link rel="stylesheet" href="./glass.css" />';
const JS_TAG = '<script src="./src/main.ts"></script>';

/** Replace exactly one occurrence, or fail the build: a renamed tag must not ship a page without its script. */
function inline(page, tag, content) {
  const at = page.indexOf(tag);
  if (at < 0 || page.indexOf(tag, at + 1) >= 0) throw new Error(`index.html must contain ${tag} exactly once`);
  return page.slice(0, at) + content + page.slice(at + tag.length);
}

export async function buildGlass({ minify: min = minify } = {}) {
  const js = await esbuild.build({
    entryPoints: [path.join(glass, 'src', 'main.ts')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    minify: min,
    legalComments: 'none',
    write: false,
    logLevel: 'silent',
  });
  // Line endings are the checkout's (CRLF on Windows); the page is the same bytes everywhere.
  const read = (f) => fs.readFileSync(path.join(glass, f), 'utf8').replace(/\r\n/g, '\n');
  const css = await esbuild.transform(read('glass.css'), {
    loader: 'css',
    // Whitespace only: syntax minification rewrites values (bold → 700),
    // which the fidelity test's computed-style diff would rightly flag.
    minifyWhitespace: min,
    legalComments: 'none',
  });
  const script = js.outputFiles[0].text.replace(/<\/(script)/gi, '<\\/$1');
  const style = css.code.replace(/<\/(style)/gi, '<\\/$1');
  let page = read('index.html');
  // Build-time comments in the skeleton are for the source reader only.
  page = page.replace(/[ \t]*<!-- scripts\/build-glass\.mjs[^>]*-->\n/g, '');
  page = inline(page, CSS_TAG, `<style>${style.trimEnd()}</style>`);
  page = inline(page, JS_TAG, `<script>${script.trimEnd()}</script>`);
  const body =
    '// GENERATED by scripts/build-glass.mjs from apps/cli/glass — do not edit.\n' +
    '// The spyglass page: one self-contained HTML document (CSS and JS inlined).\n' +
    `export const GLASS_PAGE: string = ${JSON.stringify(page)};\n`;
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== body) fs.writeFileSync(out, body);
  // Watching: also refresh the compiled module in place, so restarting a
  // workspace `lobstah glass` serves the new page without a tsc pass.
  if (watch && fs.existsSync(distOut)) fs.writeFileSync(distOut, `export const GLASS_PAGE = ${JSON.stringify(page)};\n`);
  return page;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const once = async () => {
    const t = Date.now();
    try {
      const page = await buildGlass();
      console.log(`glass: ${(page.length / 1024).toFixed(1)} KB page in ${Date.now() - t}ms → ${path.relative(root, out)}`);
    } catch (err) {
      console.error(`glass: build failed\n${err instanceof Error ? err.message : err}`);
      if (!watch) process.exit(1);
    }
  };
  await once();
  if (watch) {
    let timer;
    const rebuild = () => {
      clearTimeout(timer);
      timer = setTimeout(once, 50);
    };
    // The client also imports the pure helpers from apps/cli/src.
    fs.watch(glass, { recursive: true }, rebuild);
    for (const f of ['glass-diff.ts', 'glass-lobs.ts']) fs.watch(path.join(root, 'apps', 'cli', 'src', f), rebuild);
    console.log('glass: watching apps/cli/glass (restart `lobstah glass` to serve a rebuilt page)');
  }
}
