/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e8e5bd178769ee991e4a6b23d567037b)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	AUTH_DB: D1Database;
	GLASS_ORIGIN: "";
	API_ORIGIN: "";
	GITHUB_CLIENT_ID: "";
	GITHUB_ALLOWLIST: "[]";
	MAX_ROWS: "10000";
	MAX_FILE_BYTES: "26214400";
	MAX_ACCOUNT_BYTES: "104857600";
	REQUESTS_PER_MINUTE: "120";
	AUTH_SECRET: string;
	GITHUB_CLIENT_SECRET: string;
	TOKEN_SECRET: string;
	ACCOUNTS: DurableObjectNamespace<import("./src/index").Account>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Account";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GLASS_ORIGIN" | "API_ORIGIN" | "GITHUB_CLIENT_ID" | "GITHUB_ALLOWLIST" | "MAX_ROWS" | "MAX_FILE_BYTES" | "MAX_ACCOUNT_BYTES" | "REQUESTS_PER_MINUTE" | "AUTH_SECRET" | "GITHUB_CLIENT_SECRET" | "TOKEN_SECRET">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}